### ISSUE TITLE
Direlict-imgui

### ISSUE THREAD

**Issue by drug007** [0dyl/d-cimgui#1]
Good job!
Do you consider contributing to existing cimgui bindings and wrapper [direlict-imgui](https://code.dlang.org/packages/derelict-imgui)? That  would be really nice if you combine your efforts with others.

**Comment by hmmdyl** [comment]
Thanks!

I was considering writing into Derelict-Imgui but I didn't know how they'd react to me merging the code. This also doesn't have some helper funcs and default params that Derelict-Imgui has, so this could be considered a slight regression in features.

When I can finalise the API, I'll merge it all into Derelict-Imgui.




-------- Original message --------

**Comment by drug007** [comment]
I see. Thank you in advance!
